<?php

use PHPUnit\Framework\TestCase;
use Src\Conference;
use Src\Tests\Factories\Talks;

class ConferenceTest extends TestCase
{
    /**
     * @var Talks
     */
    private $factory;

    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->factory = new Talks();
    }

    /** @test */
    public function there_are_pending_conversations_to_be_analyzed()
    {
        $talks = $this->factory->allTalks();

        $this->assertTrue(
            (new Conference($talks))->hasTalksRemaining()
        );
    }

    /** @test */
    public function all_talks_were_analyzed()
    {
        $talks = $this->factory->allTalksEmpty();
        $confere = new Conference($talks);

        $this->assertFalse(
            (new Conference($talks))->hasTalksRemaining()
        );
    }

    /** @test */
    public function get_quantity_of_talks_by_length()
    {
        $talks = $this->factory->allTalks();

        $this->assertEquals(
            ['60' => 5, '45' => 5, '30' => 5, '5' => 1],
            (new Conference($talks))->getCountsByMinutes()
        );
    }
}