<?php

use PHPUnit\Framework\TestCase;
use Src\IO\Reader;

class ReaderTest extends TestCase
{
    /**
     * @var Reader
     */
    private $reader;

    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->reader = new Reader();
    }

    /** @test */
    public function should_return_a_valid_formatted_entry()
    {
        $title = 'New Talk For Test';

        $result = $this->reader->formatEntry("$title 1min");

        $this->assertEquals($result, [ '1', $title ]);
    }
}