<?php

use PHPUnit\Framework\TestCase;
use Src\Helpers\Validator;

class ValidatorTest extends TestCase
{
    /**
     * @var Validator
     */
    private $validator;

    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->validator = new Validator();
    }

    /** @test */
    public function validate_if_the_entries_do_not_have_number_in_the_name()
    {
        $this->validator->validateTitle('correct title');

        $this->expectException(Exception::class);

        $this->validator->validateTitle('3rr0ng title');
    }

    /** @test */
    public function sum_of_hours_of_entries_must_be_greater_than_six_hours()
    {
        $this->validator->validateMinutesLength(180);

        $this->expectException(Exception::class);

        $this->validator->validateMinutesLength(100);

    }
}